Added docker file changes for the cloudfeeds -atomhopper
rackerlabs/cloudfeeds-atomhopper pull request #38
Opened 2021-03-17 08:05 UTC by shub6691

2021-03-22 13:02 UTC, deep8103 requested changes

2021-03-22 13:02 UTC, deep8103 commented on docker/Dockerfile
> +ENV DB_TYPE=H2 \
This DB configuration is not used as of now as start.sh file is not used. We need to have a proper configuration for Postgres.

2021-03-22 13:06 UTC, deep8103 commented
This PR should have been raised against a feature branch to safeguard us from blocking any production change that goes via the master.

2021-03-23 07:44 UTC, shub6691 commented on docker/Dockerfile
> +ENV DB_TYPE=H2 \
done

2021-03-23 07:44 UTC, shub6691 commented on docker/Dockerfile
> +COPY start.sh .
removed

2021-03-23 07:45 UTC, shub6691 commented on docker/Dockerfile
> +    && curl -o atomhopper.war https://maven.research.rackspacecloud.com/content/repositories/releases/com/rackspace/feeds/feeds-atomhopper/${AH_VERSION}/feeds-atomhopper-${AH_VERSION}.war \
done

2021-03-23 07:45 UTC, shub6691 commented on docker/files/application-context.xml
> +<!--
done.

2021-03-23 07:45 UTC, shub6691 commented on docker/files/atom-server.cfg.xml
> +    <!--
done

2021-03-23 07:49 UTC, shub6691 commented on docker/repose-2018-saxon-license.lic
> +Signature=302C02145E39F15E0FD3C2FA6903AA4151D6BE836B80F28602146719D9C5EDFF90DD72018FB1A98A63044B3757DC
done

2021-03-23 08:43 UTC, shub6691 commented on pom.xml
> +                <version>2.11.0</version>
done

2021-03-23 08:43 UTC, shub6691 commented on docker/repose-2018-saxon-license.lic
> +Signature=302C02145E39F15E0FD3C2FA6903AA4151D6BE836B80F28602146719D9C5EDFF90DD72018FB1A98A63044B3757DC
done

2021-03-23 09:44 UTC, closed without merging