Added docker image for cloudfeeds atomhooper
rackerlabs/cloudfeeds-atomhopper pull request #40
Opened 2021-03-23 09:52 UTC by shub6691

2021-03-23 10:11 UTC, deep8103 commented on docker/Dockerfile
> +RUN chmod +x ${AH_HOME}/start.sh
Please remove this irrelevant line.

2021-03-23 10:24 UTC, deep8103 commented on docker/files/application-context.xml
> +  <bean id="concorde-jdbc-new-feed-read-repository-bean" class="org.apache.tomcat.jdbc.pool.DataSource">
Duplicate, replace this instance of _concorde_ with _support_

2021-03-23 10:26 UTC, deep8103 commented on docker/files/atom-server.cfg.xml
> +    <workspace title="support workspace" resource="/support/">
Duplicate, remove this occurence.

2021-03-23 10:31 UTC, deep8103 commented on docker/Dockerfile
> +ENV SAXON_HOME=/etc/saxon \
Failed to compile, change this to single ENV instruction. As given below.

ENV SAXON_HOME=/etc/saxon \
         AH_VERSION=1.9.1 \
         CATALINA_HOME=/opt/tomcat \
         AH_HOME=/opt/atomhopper  \
         PATH=${PATH}:${CATALINA_HOME}/bin:${AH_HOME}

2021-03-24 11:16 UTC, shub6691 commented on docker/Dockerfile
> +RUN chmod +x ${AH_HOME}/start.sh
Done

2021-03-24 11:16 UTC, shub6691 commented on docker/files/application-context.xml
> +  <bean id="concorde-jdbc-new-feed-read-repository-bean" class="org.apache.tomcat.jdbc.pool.DataSource">
done

2021-03-24 11:16 UTC, shub6691 commented on docker/files/atom-server.cfg.xml
> +    <workspace title="support workspace" resource="/support/">
done

2021-03-24 11:16 UTC, shub6691 commented on docker/Dockerfile
> +ENV SAXON_HOME=/etc/saxon \
done

2021-03-24 11:31 UTC, deep8103 commented on docker/Dockerfile
> +ENV SAXON_HOME=/etc/saxon
Build failed, compile issues. Replace with:
ENV SAXON_HOME=/etc/saxon \
        AH_VERSION=$ah_version \
        CATALINA_HOME=/opt/tomcat \
        AH_HOME=/opt/atomhopper \
        PATH=${PATH}:${CATALINA_HOME}/bin:${AH_HOME}

2021-03-24 11:31 UTC, deep8103 commented on README.md
> +$docker build -t cloudfeeds-atomhopper:latest-alpine .
This instruction missing mandatory arguments.

2021-03-24 11:31 UTC, deep8103 commented on README.md
> +For ex: docker build --build-arg ah_version=1.9.1 --build-arg AH_VERSION=1.136.1
misleading instruction. It should have been:
docker build --build-arg ah_version=1.9.1 --build-arg app_version=1.136.1 --build-arg saxon_lic=saxon-license.lic

2021-03-24 11:36 UTC, deep8103 requested changes

2021-03-24 11:36 UTC, deep8103 commented on docker/Dockerfile
> +    && mv feeds-atomhopper.war ${CATALINA_HOME}/webapps/ROOT.war \
Remove `\` line number 35. Received warning from docker:
[WARNING]: Empty continuation line found in:
 .
.
.
[WARNING]: Empty continuation lines will become errors in a future release.

2021-03-24 11:39 UTC, deep8103 commented on docker/Dockerfile
> +    && mv usage-schema-${APP_VERSION}/xslt-artifacts/* /etc/cloudfeeds/translation/. \
Replace AH_VERSION to app_version

2021-03-24 12:22 UTC, shub6691 commented on docker/Dockerfile
> +ENV SAXON_HOME=/etc/saxon \
done.Tested now and build is successful.

2021-03-24 12:22 UTC, shub6691 commented on docker/files/atom-server.cfg.xml
> +    <workspace title="support workspace" resource="/support/">
done

2021-03-24 12:23 UTC, shub6691 commented on docker/Dockerfile
> +ENV SAXON_HOME=/etc/saxon
fixed compile issue and build was successful

2021-03-24 12:23 UTC, shub6691 commented on README.md
> +$docker build -t cloudfeeds-atomhopper:latest-alpine .
updated .

2021-03-24 12:23 UTC, shub6691 commented on README.md
> +For ex: docker build --build-arg ah_version=1.9.1 --build-arg AH_VERSION=1.136.1
done with updated statement

2021-03-24 12:23 UTC, shub6691 commented on docker/Dockerfile
> +    && mv feeds-atomhopper.war ${CATALINA_HOME}/webapps/ROOT.war \
done.

2021-03-24 12:23 UTC, shub6691 commented on docker/Dockerfile
> +    && mv usage-schema-${APP_VERSION}/xslt-artifacts/* /etc/cloudfeeds/translation/. \
done.

2021-03-24 12:42 UTC, deep8103 commented
Able to build an image by providing proper schema_version that contains xslt artifacts.

2021-03-24 12:43 UTC, deep8103 approved these changes

2021-07-29 08:42 UTC, merged