CF-3561: EC2 Image Builder
rackerlabs/cloudfeeds-atomhopper pull request #48
Opened 2023-07-21 06:01 UTC by PaulRepo

This PR contains code changes related to creating necessary code changes in atomhopper Dockerfile for Container Image Builder pipeline.

2023-07-25 05:32 UTC, AJStieren requested changes
Can we consolidate the ARG defaults to a single location instead of repeating them on each image step? This sets the default `SCHEMA_VERSION` in three different locations so if we iterate in the future it's easy to only change some of the defaults rather than all if they're explicit throughout the file.

Sidebar: Can we change the container's logging location that is followed from the Docker tail function? This is not necessary *at all* but would be a convenience.

2023-07-25 05:32 UTC, AJStieren commented on docker/.dockerignore
> -Dockerfile*
Wait, why are we not ignoring the Dockerfile when building the image anymore?

2023-07-25 05:32 UTC, AJStieren commented on docker/Dockerfile
> +#feature_containerization
Extend the comment to the full `#ARG GIT_BRANCH="feature_containerization"` to eliminate any ambiguity for vagrants.

2023-07-25 05:32 UTC, AJStieren commented on docker/Dockerfile
> +FROM bitnami/git:latest AS fetcher
Oh wow, Bitnami is cool. Why have I never heard of this before? Also, is this why Dockerfile is being brought back from the gitignore?

2023-07-25 05:32 UTC, AJStieren commented on docker/Dockerfile
> +FROM alpine:3 as package
This didn't resolve for me the first time for some reason. Not entirely sure why, but a single retry and it went through. I tried recreating the problem but couldn't, but dropping the comment for awareness.

2023-07-25 05:32 UTC, AJStieren commented on docker/Dockerfile
> +FROM alpine:3 as package
And yes, I took it to Linux after previous difficulties on the Docker compatibility layer. It was an interrupted download when pulling the base alpine image.

2023-07-25 05:32 UTC, AJStieren commented on docker/Dockerfile
> +      rm -rf /var/lib/apt/lists/*
Okay... this worked but not entirely sure why we're doing this.

2023-08-01 17:44 UTC, PaulRepo commented on docker/.dockerignore
> -Dockerfile*
We have to pass **Dockerfile** while building the image.
If we keep this line in **dockerignore** file then the **Dockerfile** will not be sent to docker and so image will not be build.

2023-08-01 17:47 UTC, PaulRepo commented on docker/Dockerfile
> +FROM bitnami/git:latest AS fetcher
**Dockerfile** is brought back from **dockerignore** so that it is passed to docker daemon in the docker context to build the image.

2023-08-10 10:30 UTC, PaulRepo commented on docker/Dockerfile
> +#feature_containerization
Handled the code accordingly

2023-08-10 10:33 UTC, PaulRepo commented
Q. Can we consolidate the ARG defaults to a single location instead of repeating them on each image step? This sets the default SCHEMA_VERSION in three different locations so if we iterate in the future it's easy to only change some of the defaults rather than all if they're explicit throughout the file.

A. We can't, as per [official docs ](https://docs.docker.com/engine/reference/builder/#scope)

> An ARG instruction goes out of scope at the end of the build stage where it was defined. To use an argument in multiple stages, each stage must include the ARG instruction.

Anyways now I am replacing the **ARG** instruction with **ENV** so custom values can be passed to the container from ECS container definition and then no need to change it in Dockerfile

2023-08-10 16:22 UTC, PaulRepo commented
Q. Sidebar: Can we change the container's logging location that is followed from the Docker tail function? This is not necessary at all but would be a convenience.

A. Docker tail command displays the log from the main process running inside container as PID=1
So we cannot change the container's logging location

2023-08-11 16:39 UTC, PaulRepo commented on docker/Dockerfile
> +      rm -rf /var/lib/apt/lists/*
This change has been done by Kavish related to **maxdays** in server.xml by using transform.xml

2023-11-22 14:15 UTC, merged